version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/lib/postgresql/data:rw
